### ISSUE TITLE
Production builds have error in lodash file

### ISSUE THREAD

**Issue by Venryx** [Venryx/LucidLink#1]
Here is the error:
```
02-03 20:50:29.862: E/ReactNativeJS(31290): Module AppRegistry is not a registered callable module (calling runApplication)
02-03 20:50:29.868: E/AndroidRuntime(31290): FATAL EXCEPTION: mqt_native_modules
02-03 20:50:29.868: E/AndroidRuntime(31290): Process: v.lucidlink, PID: 31290
02-03 20:50:29.868: E/AndroidRuntime(31290): com.facebook.react.common.JavascriptException: undefined is not a function (evaluating 'i.push({name:t,func:r})'), stack:
02-03 20:50:29.868: E/AndroidRuntime(31290): <unknown>@460:7681
02-03 20:50:29.868: E/AndroidRuntime(31290): <unknown>@458:38119
02-03 20:50:29.868: E/AndroidRuntime(31290): oe@458:28488
02-03 20:50:29.868: E/AndroidRuntime(31290): n@460:7595
02-03 20:50:29.868: E/AndroidRuntime(31290): <unknown>@460:8065
02-03 20:50:29.868: E/AndroidRuntime(31290): <unknown>@460:8223
02-03 20:50:29.868: E/AndroidRuntime(31290): o@2:517
02-03 20:50:29.868: E/AndroidRuntime(31290): e@2:326
02-03 20:50:29.868: E/AndroidRuntime(31290): i@2:188
02-03 20:50:29.868: E/AndroidRuntime(31290): <unknown>@457:95
02-03 20:50:29.868: E/AndroidRuntime(31290): o@2:517
02-03 20:50:29.868: E/AndroidRuntime(31290): e@2:326
02-03 20:50:29.868: E/AndroidRuntime(31290): i@2:188
02-03 20:50:29.868: E/AndroidRuntime(31290): <unknown>@456:126
02-03 20:50:29.868: E/AndroidRuntime(31290): o@2:517
02-03 20:50:29.868: E/AndroidRuntime(31290): e@2:326
02-03 20:50:29.868: E/AndroidRuntime(31290): i@2:188
02-03 20:50:29.868: E/AndroidRuntime(31290): <unknown>@455:101
02-03 20:50:29.868: E/AndroidRuntime(31290): o@2:517
02-03 20:50:29.868: E/AndroidRuntime(31290): e@2:326
02-03 20:50:29.868: E/AndroidRuntime(31290): i@2:188
02-03 20:50:29.868: E/AndroidRuntime(31290): <unknown>@429:197
02-03 20:50:29.868: E/AndroidRuntime(31290): o@2:517
02-03 20:50:29.868: E/AndroidRuntime(31290): e@2:326
02-03 20:50:29.868: E/AndroidRuntime(31290): i@2:188
02-03 20:50:29.868: E/AndroidRuntime(31290): <unknown>@372:2228
02-03 20:50:29.868: E/AndroidRuntime(31290): o@2:517
02-03 20:50:29.868: E/AndroidRuntime(31290): e@2:326
02-03 20:50:29.868: E/AndroidRuntime(31290): i@2:188
02-03 20:50:29.868: E/AndroidRuntime(31290): <unknown>@371:100
02-03 20:50:29.868: E/AndroidRuntime(31290): o@2:517
02-03 20:50:29.868: E/AndroidRuntime(31290): e@2:326
02-03 20:50:29.868: E/AndroidRuntime(31290): i@2:188
02-03 20:50:29.868: E/AndroidRuntime(31290): <unknown>@12:88
02-03 20:50:29.868: E/AndroidRuntime(31290): o@2:517
02-03 20:50:29.868: E/AndroidRuntime(31290): e@2:256
02-03 20:50:29.868: E/AndroidRuntime(31290): i@2:188
02-03 20:50:29.868: E/AndroidRuntime(31290): global code@563:9
02-03 20:50:29.868: E/AndroidRuntime(31290): 	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:97)
02-03 20:50:29.868: E/AndroidRuntime(31290): 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:81)
02-03 20:50:29.868: E/AndroidRuntime(31290): 	at java.lang.reflect.Method.invoke(Native Method)
02-03 20:50:29.868: E/AndroidRuntime(31290): 	at java.lang.reflect.Method.invoke(Method.java:372)
02-03 20:50:29.868: E/AndroidRuntime(31290): 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
02-03 20:50:29.868: E/AndroidRuntime(31290): 	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
02-03 20:50:29.868: E/AndroidRuntime(31290): 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
02-03 20:50:29.868: E/AndroidRuntime(31290): 	at android.os.Handler.handleCallback(Handler.java:739)
02-03 20:50:29.868: E/AndroidRuntime(31290): 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-03 20:50:29.868: E/AndroidRuntime(31290): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
02-03 20:50:29.868: E/AndroidRuntime(31290): 	at android.os.Looper.loop(Looper.java:135)
02-03 20:50:29.868: E/AndroidRuntime(31290): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
02-03 20:50:29.868: E/AndroidRuntime(31290): 	at java.lang.Thread.run(Thread.java:818)
```

In one of the "[something]\node_modules\lodash\index.js" files (not sure which one, as I did a replace all), an error occurs until we change lines 12285-12286:
```
        var key = lodashFunc.name,
            names = names = realNames[key] || (realNames[key] = []);
```

To this:
```
        var key = lodashFunc.name,
            names = realNames[key] && realNames[key].push ? realNames[key] : (realNames[key] = []);
```

While the above fixes it, would be nice to find a way of solving it with configuration files. (instead of brittle source-code changes)

**Comment by Venryx** [comment]
Well, I'm closing it for now I guess. (haven't decided whether I should make it a policy of leaving "worked around" problems open, or close them since they're _sort of_ solved)
